### PR TITLE
Removing renovate schedule.

### PR DESCRIPTION
**Pull request by dessalines**
I have 3 CI runners now, so it seems pointless to wait for updates.

### CODE REVIEW

**Review by MV-GH — APPROVED** [review]
I thought this was more so that you wouldn't get spammed with updated. Just once a month it bundles everything.

**Comment by dessalines** [comment]
That turned out to be less annoying than I'd thought, since it's only a click of a button to merge them.

**Comment by MV-GH** [comment]
Can you add rule to the changelog so that renovate bump deps is only shown once and not per PR? Else the changelog will pretty much just become version bumps

**Comment by dessalines** [comment]
Yep I think I can do that.

**Pull request merged**
